/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AsesmenIndexRouteImport } from './routes/asesmen/index'
import { Route as IsiKodeRouteImport } from './routes/isi/$kode'
import { Route as AsesmenIdIndexRouteImport } from './routes/asesmen/$id/index'
import { Route as AsesmenIdKualitatifRouteImport } from './routes/asesmen/$id/kualitatif'
import { Route as AsesmenIdLaporanRouteImport } from './routes/asesmen/$id/laporan'
import { Route as AsesmenIdTriangulasiRouteImport } from './routes/asesmen/$id/triangulasi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AsesmenIndexRoute = AsesmenIndexRouteImport.update({
  id: '/asesmen/',
  path: '/asesmen/',
  getParentRoute: () => rootRouteImport,
} as any)
const IsiKodeRoute = IsiKodeRouteImport.update({
  id: '/isi/$kode',
  path: '/isi/$kode',
  getParentRoute: () => rootRouteImport,
} as any)
const AsesmenIdIndexRoute = AsesmenIdIndexRouteImport.update({
  id: '/asesmen/$id/',
  path: '/asesmen/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsesmenIdKualitatifRoute = AsesmenIdKualitatifRouteImport.update({
  id: '/asesmen/$id/kualitatif',
  path: '/asesmen/$id/kualitatif',
  getParentRoute: () => rootRouteImport,
} as any)
const AsesmenIdLaporanRoute = AsesmenIdLaporanRouteImport.update({
  id: '/asesmen/$id/laporan',
  path: '/asesmen/$id/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const AsesmenIdTriangulasiRoute = AsesmenIdTriangulasiRouteImport.update({
  id: '/asesmen/$id/triangulasi',
  path: '/asesmen/$id/triangulasi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/isi/$kode': typeof IsiKodeRoute
  '/asesmen/': typeof AsesmenIndexRoute
  '/asesmen/$id/kualitatif': typeof AsesmenIdKualitatifRoute
  '/asesmen/$id/laporan': typeof AsesmenIdLaporanRoute
  '/asesmen/$id/triangulasi': typeof AsesmenIdTriangulasiRoute
  '/asesmen/$id/': typeof AsesmenIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/isi/$kode': typeof IsiKodeRoute
  '/asesmen': typeof AsesmenIndexRoute
  '/asesmen/$id/kualitatif': typeof AsesmenIdKualitatifRoute
  '/asesmen/$id/laporan': typeof AsesmenIdLaporanRoute
  '/asesmen/$id/triangulasi': typeof AsesmenIdTriangulasiRoute
  '/asesmen/$id': typeof AsesmenIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/isi/$kode': typeof IsiKodeRoute
  '/asesmen/': typeof AsesmenIndexRoute
  '/asesmen/$id/kualitatif': typeof AsesmenIdKualitatifRoute
  '/asesmen/$id/laporan': typeof AsesmenIdLaporanRoute
  '/asesmen/$id/triangulasi': typeof AsesmenIdTriangulasiRoute
  '/asesmen/$id/': typeof AsesmenIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/isi/$kode'
    | '/asesmen/'
    | '/asesmen/$id/kualitatif'
    | '/asesmen/$id/laporan'
    | '/asesmen/$id/triangulasi'
    | '/asesmen/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/isi/$kode'
    | '/asesmen'
    | '/asesmen/$id/kualitatif'
    | '/asesmen/$id/laporan'
    | '/asesmen/$id/triangulasi'
    | '/asesmen/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/isi/$kode'
    | '/asesmen/'
    | '/asesmen/$id/kualitatif'
    | '/asesmen/$id/laporan'
    | '/asesmen/$id/triangulasi'
    | '/asesmen/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  IsiKodeRoute: typeof IsiKodeRoute
  AsesmenIndexRoute: typeof AsesmenIndexRoute
  AsesmenIdKualitatifRoute: typeof AsesmenIdKualitatifRoute
  AsesmenIdLaporanRoute: typeof AsesmenIdLaporanRoute
  AsesmenIdTriangulasiRoute: typeof AsesmenIdTriangulasiRoute
  AsesmenIdIndexRoute: typeof AsesmenIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asesmen/': {
      id: '/asesmen/'
      path: '/asesmen'
      fullPath: '/asesmen/'
      preLoaderRoute: typeof AsesmenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isi/$kode': {
      id: '/isi/$kode'
      path: '/isi/$kode'
      fullPath: '/isi/$kode'
      preLoaderRoute: typeof IsiKodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asesmen/$id/': {
      id: '/asesmen/$id/'
      path: '/asesmen/$id'
      fullPath: '/asesmen/$id/'
      preLoaderRoute: typeof AsesmenIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asesmen/$id/kualitatif': {
      id: '/asesmen/$id/kualitatif'
      path: '/asesmen/$id/kualitatif'
      fullPath: '/asesmen/$id/kualitatif'
      preLoaderRoute: typeof AsesmenIdKualitatifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asesmen/$id/laporan': {
      id: '/asesmen/$id/laporan'
      path: '/asesmen/$id/laporan'
      fullPath: '/asesmen/$id/laporan'
      preLoaderRoute: typeof AsesmenIdLaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asesmen/$id/triangulasi': {
      id: '/asesmen/$id/triangulasi'
      path: '/asesmen/$id/triangulasi'
      fullPath: '/asesmen/$id/triangulasi'
      preLoaderRoute: typeof AsesmenIdTriangulasiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  IsiKodeRoute: IsiKodeRoute,
  AsesmenIndexRoute: AsesmenIndexRoute,
  AsesmenIdKualitatifRoute: AsesmenIdKualitatifRoute,
  AsesmenIdLaporanRoute: AsesmenIdLaporanRoute,
  AsesmenIdTriangulasiRoute: AsesmenIdTriangulasiRoute,
  AsesmenIdIndexRoute: AsesmenIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
